Adds the ability to set the update rate of the simulation
open-rmf/rmf_demos pull request #264
Opened 2024-10-08 05:30 UTC by arjo129

## New feature implementation

### Implemented feature

This commit adds the ability to set the update rate of simulation to be faster than real time via the `update_rate` option.

For instance if you want a 5x real time factor simulation running via CLI simply add the flags:

```
ros2 launch rmf_demos_gz office.launch.xml update_rate:=5000
```
Note by default this sets gazebo's internal step size. Usually we have 1000 steps per second of simulation, hence if we want 5x RTF we need to set update_rate:=5000.

2024-10-09 17:18 UTC, Yadunund requested changes
imo  `update_rate` sounds very ambiguous since it's not clear what this is referring to along with the units. There is room to think it updates the rate of the fleet adapter updates for example. How about `sim_update_rate`?

2024-10-10 01:35 UTC, luca-della-vedova commented
The default step size for rmf simulations is [0.01](https://github.com/open-rmf/rmf_traffic_editor/blob/71e419c9cda7fa17d47055ded3445859c542979e/rmf_building_map_tools/building_map/templates/gz_world.sdf#L5) though, not 0.001, does the command line argument also set the step size to 0.001 behind the scenes or would this make the simulation run at 10x RTF by default?

2024-10-10 02:53 UTC, arjo129 commented
> The default step size for rmf simulations is [0.01](https://github.com/open-rmf/rmf_traffic_editor/blob/71e419c9cda7fa17d47055ded3445859c542979e/rmf_building_map_tools/building_map/templates/gz_world.sdf#L5) though, not 0.001, does the command line argument also set the step size to 0.001 behind the scenes or would this make the simulation run at 10x RTF by default?

You are right this is my mistake, I've changed the defaults.

2024-10-11 18:16 UTC, Yadunund approved these changes

2024-10-11 18:16 UTC, merged